import { makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  profile: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    padding: theme.spacing(1, 0),
    overflowX: "hidden",
    [theme.breakpoints.down("xs")]: {
      padding: 0,
    },
  },
  card: {
    width: "100%",
    maxWidth: 560,
    paddingBottom: theme.spacing(3),
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    textAlign: "left",
    overflow: "hidden",
    borderRadius: 8,
    boxSizing: "border-box",
    [theme.breakpoints.down("xs")]: {
      borderRadius: 0,
      boxShadow: "none",
    },
  },
  backButtonRow: {
    width: "100%",
    padding: theme.spacing(1, 1, 0, 1),
    boxSizing: "border-box",
  },
  backButton: {
    minHeight: 44,
    borderRadius: 22,
    textTransform: "none",
    color: "#2e7d32",
    fontWeight: 600,
    padding: theme.spacing(0.75, 1.5),
  },
  coverArea: {
    width: "100%",
    height: "clamp(88px, 24vw, 120px)",
    background: "linear-gradient(135deg, #2e7d32 0%, #1b5e20 100%)",
    position: "relative",
    marginBottom: 52,
    [theme.breakpoints.down("xs")]: {
      marginBottom: 44,
    },
  },
  coverAreaWithImage: {
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
  },
  avatar: {
    width: 104,
    height: 104,
    border: `4px solid ${theme.palette.background.paper}`,
    position: "absolute",
    bottom: -52,
    left: 16,
    [theme.breakpoints.down("xs")]: {
      width: 88,
      height: 88,
      bottom: -44,
      left: 12,
    },
  },
  hiddenInput: {
    display: "none",
  },
  photoUploadButton: {
    position: "absolute",
    right: 16,
    bottom: 12,
    textTransform: "none",
    borderRadius: 16,
    backgroundColor: "#2e7d32",
    color: "#fff",
    fontWeight: 600,
    padding: theme.spacing(0.5, 1.5),
    "&:hover": {
      backgroundColor: "#1b5e20",
    },
    "&.Mui-disabled": {
      backgroundColor: "#9e9e9e",
      color: "#fff",
    },
    [theme.breakpoints.down("xs")]: {
      right: 12,
      bottom: 10,
      padding: theme.spacing(0.5, 1.25),
      fontSize: "0.75rem",
    },
  },
  coverUploadButton: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 32,
    height: 32,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    color: "#2e7d32",
    border: "1px solid rgba(46, 125, 50, 0.35)",
    "&:hover": {
      backgroundColor: "#fff",
    },
    "&.Mui-disabled": {
      color: "#9e9e9e",
      borderColor: "rgba(158, 158, 158, 0.4)",
      backgroundColor: "rgba(255, 255, 255, 0.85)",
    },
  },
  name: {
    fontWeight: 700,
    fontSize: "1.25rem",
    padding: theme.spacing(0, 2),
    wordBreak: "break-word",
    minWidth: 0,
  },
  photoUploadError: {
    color: theme.palette.error.main,
    padding: theme.spacing(0.5, 2, 0, 2),
    fontSize: "0.8rem",
  },
  title: {
    color: theme.palette.text.secondary,
    padding: theme.spacing(0.5, 2, 0, 2),
    fontSize: "0.875rem",
    lineHeight: 1.5,
    wordBreak: "break-word",
    minWidth: 0,
  },
  metaRow: {
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(0.5),
    padding: theme.spacing(1, 2, 0, 2),
    width: "100%",
    boxSizing: "border-box",
    minWidth: 0,
  },
  metaItem: {
    display: "flex",
    alignItems: "center",
    fontSize: "0.8rem",
    minWidth: 0,
    "& > .MuiSvgIcon-root": {
      flexShrink: 0,
    },
    "& > span": {
      minWidth: 0,
      wordBreak: "break-word",
    },
  },
  section: {
    width: "100%",
    padding: theme.spacing(0, 2),
    boxSizing: "border-box",
    minWidth: 0,
  },
  networkMeta: {
    color: "#2e7d32",
    fontSize: "0.8rem",
    wordBreak: "break-word",
  },
  actionRow: {
    width: "100%",
    padding: theme.spacing(0, 2),
    boxSizing: "border-box",
    marginTop: 12,
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    minWidth: 0,
  },
  connectionsPanel: {
    width: "100%",
    marginTop: 12,
    padding: theme.spacing(0, 2),
    boxSizing: "border-box",
  },
  connectionsPanelHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  connectionsPanelTitle: {
    fontWeight: 700,
  },
  closeConnectionsButton: {
    textTransform: "none",
    color: "#2e7d32",
    minHeight: 36,
    borderRadius: 18,
    fontWeight: 600,
  },
  connectionsList: {
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(1),
  },
  connectionCard: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1.25),
    border: "1px solid rgba(46, 125, 50, 0.25)",
    borderRadius: 10,
    padding: theme.spacing(1),
    cursor: "pointer",
    transition: "background-color 0.2s ease, border-color 0.2s ease",
    "&:hover, &:focus": {
      outline: "none",
      backgroundColor: "rgba(46, 125, 50, 0.06)",
      borderColor: "rgba(46, 125, 50, 0.45)",
    },
  },
  connectionAvatar: {
    width: 40,
    height: 40,
  },
  connectionCardInfo: {
    minWidth: 0,
  },
  connectionCardName: {
    fontWeight: 600,
    fontSize: "0.9rem",
    lineHeight: 1.3,
    wordBreak: "break-word",
  },
  connectionCardTitle: {
    color: theme.palette.text.secondary,
    fontSize: "0.8rem",
    lineHeight: 1.4,
    wordBreak: "break-word",
  },
  tabs: {
    width: "100%",
    minWidth: 0,
  },
  tab: {
    minWidth: 0,
  },
  postsSection: {
    marginTop: 8,
  },
  postsList: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(1.5),
    paddingBottom: theme.spacing(1),
    minWidth: 0,
    "& > *": {
      width: "100%",
      maxWidth: "100%",
      minWidth: 0,
      boxSizing: "border-box",
    },
  },
  activityList: {
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(1),
    padding: theme.spacing(1, 0),
  },
  activityCard: {
    border: "1px solid rgba(46, 125, 50, 0.2)",
    borderRadius: 10,
    padding: theme.spacing(1.25, 1.5),
    backgroundColor: "#fff",
  },
  activityHeading: {
    fontSize: "0.8rem",
    fontWeight: 700,
    color: "#1b5e20",
    marginBottom: 2,
  },
  activityTimestamp: {
    fontSize: "0.75rem",
    color: theme.palette.text.secondary,
    marginBottom: 8,
  },
  activityBody: {
    fontSize: "0.88rem",
    lineHeight: 1.5,
    color: theme.palette.text.primary,
    whiteSpace: "pre-line",
    wordBreak: "break-word",
  },
  activityContext: {
    marginTop: 8,
    fontSize: "0.8rem",
    lineHeight: 1.45,
    color: theme.palette.text.secondary,
    wordBreak: "break-word",
  },
}));
