import { makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  profile: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    padding: theme.spacing(1, 0),
    overflowX: "hidden",
    [theme.breakpoints.down("xs")]: {
      padding: 0,
    },
  },
  card: {
    width: "100%",
    maxWidth: 560,
    paddingBottom: theme.spacing(3),
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    textAlign: "left",
    overflow: "hidden",
    borderRadius: 8,
    boxSizing: "border-box",
    [theme.breakpoints.down("xs")]: {
      borderRadius: 0,
      boxShadow: "none",
    },
  },
  backButtonRow: {
    width: "100%",
    padding: theme.spacing(1, 1, 0, 1),
    boxSizing: "border-box",
  },
  backButton: {
    minHeight: 44,
    borderRadius: 22,
    textTransform: "none",
    color: "#2e7d32",
    fontWeight: 600,
    padding: theme.spacing(0.75, 1.5),
  },
  coverArea: {
    width: "100%",
    height: "clamp(88px, 24vw, 120px)",
    background: "linear-gradient(135deg, #2e7d32 0%, #1b5e20 100%)",
    position: "relative",
    marginBottom: 52,
    [theme.breakpoints.down("xs")]: {
      marginBottom: 44,
    },
  },
  avatar: {
    width: 104,
    height: 104,
    border: "4px solid #fff",
    position: "absolute",
    bottom: -52,
    left: 16,
    [theme.breakpoints.down("xs")]: {
      width: 88,
      height: 88,
      bottom: -44,
      left: 12,
    },
  },
  name: {
    fontWeight: 700,
    fontSize: "1.25rem",
    padding: theme.spacing(0, 2),
    wordBreak: "break-word",
    minWidth: 0,
  },
  title: {
    color: theme.palette.text.secondary,
    padding: theme.spacing(0.5, 2, 0, 2),
    fontSize: "0.875rem",
    lineHeight: 1.5,
    wordBreak: "break-word",
    minWidth: 0,
  },
  metaRow: {
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(0.5),
    padding: theme.spacing(1, 2, 0, 2),
    width: "100%",
    boxSizing: "border-box",
    minWidth: 0,
  },
  metaItem: {
    display: "flex",
    alignItems: "center",
    fontSize: "0.8rem",
    minWidth: 0,
    "& > .MuiSvgIcon-root": {
      flexShrink: 0,
    },
    "& > span": {
      minWidth: 0,
      wordBreak: "break-word",
    },
  },
  section: {
    width: "100%",
    padding: theme.spacing(0, 2),
    boxSizing: "border-box",
    minWidth: 0,
  },
  networkMeta: {
    color: "#2e7d32",
    fontSize: "0.8rem",
    wordBreak: "break-word",
  },
  actionRow: {
    width: "100%",
    padding: theme.spacing(0, 2),
    boxSizing: "border-box",
    marginTop: 12,
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    minWidth: 0,
  },
  tabs: {
    width: "100%",
    minWidth: 0,
  },
  tab: {
    minWidth: 0,
  },
  postsSection: {
    marginTop: 8,
  },
  postsList: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(1.5),
    paddingBottom: theme.spacing(1),
    minWidth: 0,
    "& > *": {
      width: "100%",
      maxWidth: "100%",
      minWidth: 0,
      boxSizing: "border-box",
    },
  },
}));
