import { fade, makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  root: {
    width: "100%",
    height: "calc(100vh - 170px)",
    minHeight: 460,
    display: "flex",
    flexDirection: "column",
    borderRadius: 8,
    overflow: "hidden",
    [theme.breakpoints.down("xs")]: {
      borderRadius: 0,
      height: "calc(100vh - 110px)",
      minHeight: 0,
    },
  },
  listView: {
    width: "100%",
    height: "100%",
    overflowY: "auto",
  },
  listHeader: {
    padding: "20px 20px 14px",
    position: "sticky",
    top: 0,
    backgroundColor: theme.palette.background.paper,
    zIndex: 1,
    [theme.breakpoints.down("xs")]: {
      padding: "16px 16px 12px",
    },
  },
  avatar: {
    width: 48,
    height: 48,
    fontSize: 18,
    fontWeight: 600,
    letterSpacing: "0.02em",
    flexShrink: 0,
    [theme.breakpoints.down("xs")]: {
      width: 44,
      height: 44,
      fontSize: 16,
    },
  },
  conversationItem: {
    width: "100%",
    minWidth: 0,
    border: 0,
    background: "transparent",
    borderRadius: 0,
    textAlign: "left",
    textTransform: "none",
    padding: "14px 20px",
    cursor: "pointer",
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 14,
    transition: "background-color 0.15s ease",
    "&:hover": {
      backgroundColor: theme.palette.action.hover,
    },
    "& + &": {
      borderTop: `1px solid ${fade(theme.palette.divider, 0.6)}`,
    },
    [theme.breakpoints.down("xs")]: {
      padding: "12px 16px",
      gap: 12,
    },
  },
  conversationMain: {
    flex: 1,
    minWidth: 0,
  },
  conversationTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  conversationName: {
    fontSize: 15,
    fontWeight: 600,
    color: theme.palette.text.primary,
    margin: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    letterSpacing: "-0.01em",
    [theme.breakpoints.down("xs")]: {
      fontSize: 14,
    },
  },
  conversationTime: {
    color: theme.palette.text.secondary,
    fontSize: 12,
    whiteSpace: "nowrap",
    fontWeight: 500,
  },
  conversationPreview: {
    marginTop: 3,
    color: theme.palette.text.secondary,
    fontSize: 13,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    lineHeight: 1.4,
  },
  emptyState: {
    flex: 1,
    minHeight: 220,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.palette.text.secondary,
    padding: 20,
    textAlign: "center",
  },
  loadingState: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  threadHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderBottom: `1px solid ${theme.palette.divider}`,
    backgroundColor: theme.palette.background.paper,
  },
  backButton: {
    color: theme.palette.primary.main,
    backgroundColor: fade(theme.palette.primary.main, 0.08),
    width: 40,
    height: 40,
    padding: 8,
    "&:hover": {
      backgroundColor: fade(theme.palette.primary.main, 0.14),
    },
  },
  threadTitle: {
    fontWeight: 600,
    fontSize: 15,
    color: theme.palette.text.primary,
  },
  messageList: {
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: "14px 12px",
    backgroundColor: theme.palette.background.default,
  },
  messageRow: {
    display: "flex",
    width: "100%",
  },
  ownRow: {
    justifyContent: "flex-end",
  },
  otherRow: {
    justifyContent: "flex-start",
  },
  bubble: {
    maxWidth: "78%",
    padding: "8px 12px",
    borderRadius: 14,
    boxShadow: "0 1px 1px rgba(0, 0, 0, 0.08)",
  },
  ownBubble: {
    backgroundColor: theme.palette.primary.main,
    color: "#fff",
    borderBottomRightRadius: 6,
  },
  otherBubble: {
    backgroundColor: theme.palette.type === "dark" ? "#2a2e32" : "#f0f0f0",
    color: theme.palette.text.primary,
    borderBottomLeftRadius: 6,
  },
  messageText: {
    fontSize: 14,
    lineHeight: 1.35,
    wordBreak: "break-word",
  },
  messageMeta: {
    marginTop: 4,
    fontSize: 11,
    opacity: 0.85,
  },
  inputBar: {
    borderTop: `1px solid ${theme.palette.divider}`,
    padding: "10px 12px",
    display: "flex",
    alignItems: "center",
    gap: 8,
    backgroundColor: theme.palette.background.paper,
    position: "sticky",
    bottom: 0,
    zIndex: 2,
    [theme.breakpoints.down("xs")]: {
      paddingBottom: "calc(10px + env(safe-area-inset-bottom, 0px))",
    },
  },
  inputField: {
    flex: 1,
  },
  sendButton: {
    minWidth: 90,
    backgroundColor: theme.palette.primary.main,
    color: "#fff",
    textTransform: "none",
    "&:hover": {
      backgroundColor: theme.palette.primary.dark,
    },
    "&.Mui-disabled": {
      color: "rgba(255,255,255,0.8)",
      backgroundColor: "#9e9e9e",
    },
  },
}));
