import { makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  root: {
    width: "100%",
    height: "calc(100vh - 170px)",
    minHeight: 460,
    display: "flex",
    flexDirection: "column",
    borderRadius: 8,
    overflow: "hidden",
    [theme.breakpoints.down("xs")]: {
      borderRadius: 0,
      height: "calc(100vh - 110px)",
      minHeight: 0,
    },
  },
  listView: {
    width: "100%",
    height: "100%",
    overflowY: "auto",
  },
  listHeader: {
    padding: "16px 18px 8px",
    borderBottom: `1px solid ${theme.palette.divider}`,
    position: "sticky",
    top: 0,
    backgroundColor: theme.palette.background.paper,
    zIndex: 1,
  },
  conversationItem: {
    width: "100%",
    border: 0,
    background: "transparent",
    textAlign: "left",
    padding: "12px 16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 12,
    borderBottom: `1px solid ${theme.palette.divider}`,
    transition: "background-color 0.2s ease",
    "&:hover": {
      backgroundColor: theme.palette.action.hover,
    },
  },
  conversationMain: {
    flex: 1,
    minWidth: 0,
  },
  conversationTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  conversationName: {
    fontSize: 14,
    fontWeight: 600,
    color: theme.palette.text.primary,
    margin: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  conversationTime: {
    color: theme.palette.text.secondary,
    fontSize: 11,
    whiteSpace: "nowrap",
  },
  conversationPreview: {
    marginTop: 2,
    color: theme.palette.text.secondary,
    fontSize: 13,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  emptyState: {
    flex: 1,
    minHeight: 220,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.palette.text.secondary,
    padding: 20,
    textAlign: "center",
  },
  loadingState: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  threadHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    borderBottom: `1px solid ${theme.palette.divider}`,
    backgroundColor: theme.palette.background.paper,
  },
  backButton: {
    color: "#2e7d32",
    backgroundColor: "#f1f8f1",
    width: 44,
    height: 44,
    padding: 10,
    "&:hover": {
      backgroundColor: "#e3f2e5",
    },
  },
  threadTitle: {
    fontWeight: 600,
    fontSize: 15,
    color: theme.palette.text.primary,
  },
  messageList: {
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: "14px 12px",
    backgroundColor: theme.palette.background.default,
  },
  messageRow: {
    display: "flex",
    width: "100%",
  },
  ownRow: {
    justifyContent: "flex-end",
  },
  otherRow: {
    justifyContent: "flex-start",
  },
  bubble: {
    maxWidth: "78%",
    padding: "8px 12px",
    borderRadius: 14,
    boxShadow: "0 1px 1px rgba(0, 0, 0, 0.08)",
  },
  ownBubble: {
    backgroundColor: "#2e7d32",
    color: "#fff",
    borderBottomRightRadius: 6,
  },
  otherBubble: {
    backgroundColor: theme.palette.type === "dark" ? "#37474f" : "#e0e0e0",
    color: theme.palette.text.primary,
    borderBottomLeftRadius: 6,
  },
  messageText: {
    fontSize: 14,
    lineHeight: 1.35,
    wordBreak: "break-word",
  },
  messageMeta: {
    marginTop: 4,
    fontSize: 11,
    opacity: 0.85,
  },
  inputBar: {
    borderTop: `1px solid ${theme.palette.divider}`,
    padding: "10px 12px",
    display: "flex",
    alignItems: "center",
    gap: 8,
    backgroundColor: theme.palette.background.paper,
    position: "sticky",
    bottom: 0,
    zIndex: 2,
    [theme.breakpoints.down("xs")]: {
      paddingBottom: "calc(10px + env(safe-area-inset-bottom, 0px))",
    },
  },
  inputField: {
    flex: 1,
  },
  sendButton: {
    minWidth: 90,
    backgroundColor: "#2e7d32",
    color: "#fff",
    textTransform: "none",
    "&:hover": {
      backgroundColor: "#1b5e20",
    },
    "&.Mui-disabled": {
      color: "rgba(255,255,255,0.8)",
      backgroundColor: "#9e9e9e",
    },
  },
}));
