import { fade, makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  post: {
    width: "100%",
    height: "auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginTop: 8,
    borderRadius: 12,
    transition: "border-color 0.18s ease",
    "&:hover": {
      borderColor: theme.palette.type === "dark" ? "rgba(255,255,255,0.15)" : "rgba(0,0,0,0.12)",
    },
    [theme.breakpoints.down("xs")]: {
      borderRadius: 0,
      border: 0,
      boxShadow: "none",
    },
  },
  repost__header: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "10px 10px 0",
    color: theme.palette.text.secondary,
  },
  repost__headerIcon: {
    fontSize: "16px !important",
    color: theme.palette.text.secondary,
  },
  repost__headerText: {
    fontSize: 12,
    lineHeight: 1.4,
    fontWeight: 500,
    color: theme.palette.text.secondary,
    "&[role='button']": {
      cursor: "pointer",
    },
    "&[role='button']:hover": {
      textDecoration: "underline",
    },
    "&[role='button']:focus": {
      outline: `2px solid ${theme.palette.primary.main}`,
      outlineOffset: 1,
      borderRadius: 3,
    },
  },
  post__header: {
    width: "100%",
    height: "auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 20px 8px",
    "& > .MuiAvatar-root": {
    },
    "& > svg": {
      color: theme.palette.text.secondary,
      cursor: "pointer",
      borderRadius: 999,
      transition: "background-color 0.2s ease",
      "&:hover": {
        backgroundColor: theme.palette.action.hover,
      },
    },
  },
  header__info: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    marginLeft: 12,
    "& > h4": {
      fontSize: 14,
      fontWeight: 600,
      marginBottom: 2,
      letterSpacing: "-0.01em",
    },
  },
  header__meta: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    "& > p": {
      margin: 0,
      color: theme.palette.text.secondary,
      fontSize: 12,
    },
  },
  editedBadge: {
    background: "none",
    border: "none",
    margin: 0,
    padding: 0,
    color: theme.palette.text.secondary,
    fontSize: 12,
    lineHeight: 1.2,
    fontWeight: 600,
    cursor: "pointer",
    textDecoration: "underline",
    "&:focus": {
      outline: `2px solid ${theme.palette.primary.main}`,
      outlineOffset: 1,
      borderRadius: 2,
    },
  },
  post__body: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
  },
  body__description: {
    display: "flex",
    alignItems: "center",
    padding: "4px 20px 12px",
    "& > p": {
      fontSize: 14,
      margin: 0,
      width: "100%",
      wordBreak: "break-word",
    },
  },
  body__article: {
    width: "100%",
    padding: "8px 10px 10px",
  },
  articleCard: {
    width: "100%",
    border: `1px solid ${theme.palette.type === "dark" ? "#2f6f34" : "#cfe3d1"}`,
    background:
      theme.palette.type === "dark"
        ? `linear-gradient(135deg, ${fade(theme.palette.primary.main, 0.2)}, rgba(31, 36, 42, 0.9))`
        : "linear-gradient(135deg, #f2f8f3, #ffffff)",
    borderRadius: 10,
    padding: "12px 14px",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 8,
    textAlign: "left",
    cursor: "pointer",
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    "&:hover": {
      borderColor: theme.palette.primary.main,
      boxShadow: `0 0 0 1px ${fade(theme.palette.primary.main, 0.2)}`,
    },
    "&:focus-visible": {
      outline: `2px solid ${theme.palette.primary.main}`,
      outlineOffset: 2,
    },
  },
  articleBadge: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: theme.palette.type === "dark" ? "#a5d6a7" : theme.palette.primary.main,
  },
  articleTitle: {
    margin: 0,
    fontSize: 20,
    lineHeight: 1.25,
    fontWeight: 700,
    color: theme.palette.text.primary,
    wordBreak: "break-word",
  },
  articlePreview: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.5,
    color: theme.palette.type === "dark" ? "#c5d0d5" : "#4f5b67",
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 3,
    overflow: "hidden",
  },
  articleCta: {
    fontSize: 13,
    fontWeight: 600,
    color: theme.palette.type === "dark" ? "#81c784" : theme.palette.primary.main,
  },
  hashtag: {
    color: theme.palette.type === "dark" ? "#81c784" : theme.palette.primary.main,
    cursor: "pointer",
    fontWeight: 600,
    "&:hover": {
      textDecoration: "underline",
    },
    "&:focus": {
      outline: `2px solid ${theme.palette.type === "dark" ? "#81c784" : theme.palette.primary.main}`,
      outlineOffset: 1,
      borderRadius: 2,
    },
  },
  mention: {
    color: theme.palette.type === "dark" ? "#90caf9" : "#0a66c2",
    cursor: "pointer",
    fontWeight: 600,
    textDecoration: "none",
    "&:hover": {
      textDecoration: "underline",
    },
    "&:focus": {
      outline: `2px solid ${theme.palette.type === "dark" ? "#90caf9" : "#0a66c2"}`,
      outlineOffset: 1,
      borderRadius: 2,
    },
  },
  link: {
    color: theme.palette.type === "dark" ? "#90caf9" : "#0a66c2",
    textDecoration: "none",
    wordBreak: "break-all",
    "&:hover": {
      textDecoration: "underline",
    },
    "&:focus": {
      outline: `2px solid ${theme.palette.type === "dark" ? "#90caf9" : "#0a66c2"}`,
      outlineOffset: 1,
      borderRadius: 2,
    },
  },
  body__linkPreview: {
    width: "100%",
    padding: "0 10px 10px",
  },
  linkPreviewCard: {
    width: "100%",
    display: "block",
    textDecoration: "none",
    borderRadius: 8,
    border: `1px solid ${theme.palette.type === "dark" ? "#455a64" : "#dce6f1"}`,
    backgroundColor: theme.palette.type === "dark" ? theme.palette.action.hover : "#f3f8ff",
    padding: "10px 12px",
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    "&:hover": {
      borderColor: theme.palette.primary.main,
      boxShadow: `0 0 0 1px ${fade(theme.palette.primary.main, 0.2)}`,
    },
    "& > h5": {
      margin: 0,
      fontSize: 13,
      fontWeight: 600,
      color: theme.palette.text.primary,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    "& > p": {
      margin: "4px 0 0",
      fontSize: 13,
      color: theme.palette.type === "dark" ? "#b0bec5" : "#4f5b67",
      overflowWrap: "anywhere",
    },
  },
  editTextarea: {
    width: "100%",
    "& .MuiOutlinedInput-root": {
      backgroundColor: theme.palette.background.paper,
      color: theme.palette.text.primary,
      fontFamily: "inherit",
      fontSize: 14,
      "& .MuiOutlinedInput-notchedOutline": {
        borderColor: theme.palette.divider,
      },
      "&:hover .MuiOutlinedInput-notchedOutline": {
        borderColor: theme.palette.text.secondary,
      },
      "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
        borderColor: theme.palette.primary.main,
      },
    },
    "& .MuiOutlinedInput-inputMultiline": {
      padding: 8,
      resize: "vertical",
    },
  },
  editActions: {
    display: "flex",
    gap: 8,
    marginTop: 8,
  },
  saveButton: {
    backgroundColor: theme.palette.primary.main,
    color: theme.palette.common.white,
    border: "none",
    padding: "6px 16px",
    borderRadius: 20,
    cursor: "pointer",
    fontWeight: 600,
    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.6,
    },
  },
  cancelButton: {
    backgroundColor: "transparent",
    color: theme.palette.text.primary,
    border: `1px solid ${theme.palette.divider}`,
    padding: "6px 16px",
    borderRadius: 20,
    cursor: "pointer",
  },
  body__image: {
    width: "100%",
    overflow: "hidden",
    borderRadius: 8,
    "& > div": {
      height: "auto",
    },
  },
  repost__embed: {
    width: "100%",
    marginTop: 6,
    border: `1px solid ${theme.palette.type === "dark" ? "#455a64" : "#d7dbe0"}`,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: theme.palette.background.paper,
  },
  repost__embedHeader: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 10px 8px",
  },
  repost__embedAvatar: {
    width: 36,
    height: 36,
  },
  repost__embedInfo: {
    flex: 1,
    minWidth: 0,
    "& > h5": {
      margin: 0,
      fontSize: 14,
      fontWeight: 600,
      color: theme.palette.text.primary,
    },
    "& > p": {
      margin: "2px 0 0",
      fontSize: 12,
      color: theme.palette.text.secondary,
    },
  },
  repost__embedDescription: {
    margin: 0,
    padding: "0 10px 10px",
    fontSize: 14,
    color: theme.palette.text.primary,
    wordBreak: "break-word",
    whiteSpace: "pre-wrap",
  },
  body__imageGrid: {
    width: "100%",
    display: "grid",
    gap: 2,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: theme.palette.type === "dark" ? "#1f2a30" : "#f3f2ef",
  },
  imageGrid1: {
    gridTemplateColumns: "1fr",
    "& $imageGridItem": {
      minHeight: 320,
      [theme.breakpoints.down("xs")]: {
        minHeight: 220,
      },
    },
  },
  imageGrid2: {
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    [theme.breakpoints.down("xs")]: {
      gridTemplateColumns: "1fr",
    },
    "& $imageGridItem": {
      minHeight: 220,
      [theme.breakpoints.down("xs")]: {
        minHeight: 200,
      },
    },
  },
  imageGrid3: {
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    [theme.breakpoints.down("xs")]: {
      gridTemplateColumns: "1fr",
    },
    "& $imageGridItem:first-child": {
      gridColumn: "1 / span 2",
      [theme.breakpoints.down("xs")]: {
        gridColumn: "auto",
      },
    },
  },
  imageGrid4: {
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    [theme.breakpoints.down("xs")]: {
      gridTemplateColumns: "1fr",
    },
  },
  imageGridItem: {
    width: "100%",
    minHeight: 190,
    backgroundColor: theme.palette.type === "dark" ? "#101214" : "#e7ebef",
    [theme.breakpoints.down("xs")]: {
      minHeight: 145,
    },
    "& > img": {
      width: "100%",
      height: "100%",
      display: "block",
      objectFit: "cover",
    },
  },
  post__footer: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    padding: "8px 20px 0",
  },
  footer__stats: {
    display: "flex",
    alignItems: "center",
    paddingBottom: 10,
    borderBottom: `1px solid ${theme.palette.divider}`,
    "& > div": {
      display: "flex",
      "& > svg": {
        width: 16,
        height: 16,
      },
    },
    "& > h4": {
      fontSize: 12,
      fontWeight: 400,
      color: theme.palette.text.secondary,
      marginLeft: 4,
    },
  },
  reactionSummary: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    cursor: "default",
    "&:hover $reactionBreakdown": {
      opacity: 1,
      transform: "translateY(0)",
      pointerEvents: "auto",
    },
  },
  reactionIconStack: {
    display: "flex",
    alignItems: "center",
    marginRight: 2,
  },
  reactionIconBadge: {
    width: 16,
    height: 16,
    borderRadius: "50%",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: `1px solid ${theme.palette.background.paper}`,
    marginLeft: -4,
    "&:first-child": {
      marginLeft: 0,
    },
  },
  reactionIconGlyph: {
    fontSize: "10px !important",
    color: `${theme.palette.common.white} !important`,
  },
  reactionBreakdown: {
    position: "absolute",
    left: 0,
    bottom: "calc(100% + 8px)",
    zIndex: 4,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minWidth: 146,
    padding: 8,
    borderRadius: 8,
    backgroundColor: theme.palette.background.paper,
    border: `1px solid ${theme.palette.type === "dark" ? "#455a64" : "#d7dbe0"}`,
    boxShadow:
      theme.palette.type === "dark"
        ? "0 8px 24px rgba(0, 0, 0, 0.42)"
        : "0 8px 24px rgba(15, 23, 42, 0.16)",
    opacity: 0,
    transform: "translateY(6px)",
    pointerEvents: "none",
    transition: "opacity 0.15s ease, transform 0.15s ease",
  },
  reactionBreakdownItem: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: theme.palette.text.primary,
    fontSize: 12,
  },
  reactionBreakdownIcon: {
    fontSize: "14px !important",
  },
  reactionBreakdownLabel: {
    flex: 1,
    color: theme.palette.text.primary,
  },
  reactionBreakdownCount: {
    color: theme.palette.text.secondary,
    fontWeight: 600,
  },
  footer__actions: {
    display: "flex",
    justifyContent: "space-evenly",
    alignItems: "center",
    padding: 4,
    [theme.breakpoints.down("xs")]: {
      padding: 0,
    },
  },
  reactionActionWrapper: {
    flex: 1,
    position: "relative",
    display: "flex",
  },
  reactionPicker: {
    position: "absolute",
    left: "50%",
    bottom: "calc(100% + 8px)",
    transform: "translateX(-50%)",
    zIndex: 5,
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 8px",
    borderRadius: 999,
    border: `1px solid ${theme.palette.type === "dark" ? "#455a64" : "#d7dbe0"}`,
    backgroundColor: theme.palette.background.paper,
    boxShadow:
      theme.palette.type === "dark"
        ? "0 8px 22px rgba(0, 0, 0, 0.42)"
        : "0 8px 22px rgba(15, 23, 42, 0.18)",
  },
  reactionPickerButton: {
    width: 30,
    height: 30,
    border: 0,
    borderRadius: "50%",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    padding: 0,
    backgroundColor: "transparent",
    transition: "transform 0.14s ease, background-color 0.14s ease",
    "&:hover": {
      transform: "translateY(-3px) scale(1.1)",
      backgroundColor: theme.palette.action.hover,
    },
    "&:focus-visible": {
      outline: `2px solid ${theme.palette.primary.main}`,
      outlineOffset: 2,
    },
  },
  reactionPickerButtonActive: {
    backgroundColor: theme.palette.action.hover,
    transform: "translateY(-2px)",
  },
  reactionPickerIcon: {
    fontSize: "19px !important",
  },
  action__icons: {
    flex: 1,
    display: "flex",
    [theme.breakpoints.down("sm")]: {
      flexDirection: "column",
      padding: "5px 0",
    },
    justifyContent: "center",
    alignItems: "center",
    marginRight: 2,
    padding: "10px 0",
    borderRadius: 8,
    cursor: "pointer",
    transition: "all 0.18s ease",
    color: theme.palette.text.secondary,
    "&:hover": {
      backgroundColor: theme.palette.type === "dark" ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.04)",
      color: theme.palette.text.primary,
    },
    [theme.breakpoints.down("xs")]: {
      "&:hover": {
        backgroundColor: "transparent",
      },
    },
    "& > svg": {
      width: 18,
      height: 18,
      color: theme.palette.text.secondary,
      [theme.breakpoints.down("xs")]: {
        width: 14,
        height: 14,
      },
    },
    "& > h4": {
      fontSize: 12,
      fontWeight: 400,
      color: theme.palette.text.secondary,
      marginLeft: 4,
      [theme.breakpoints.down("xs")]: {
        fontSize: 12,
      },
    },
  },
  comments__section: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: "12px 16px 16px",
    borderTop: `1px solid ${theme.palette.divider}`,
  },
  comments__list: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    maxHeight: 260,
    overflowY: "auto",
    paddingRight: 4,
  },
  comment__item: {
    width: "100%",
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
  },
  comment__avatar: {
    width: 32,
    height: 32,
  },
  comment__content: {
    flex: 1,
    padding: "8px 10px",
    borderRadius: 12,
    backgroundColor: theme.palette.type === "dark" ? theme.palette.action.hover : "#f3f2ef",
    "& > p": {
      marginTop: 4,
      fontSize: 13,
      color: theme.palette.text.primary,
      wordBreak: "break-word",
    },
  },
  comment__meta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    "& > h5": {
      margin: 0,
      fontSize: 13,
      fontWeight: 600,
      color: theme.palette.text.primary,
    },
    "& > span": {
      fontSize: 11,
      color: theme.palette.text.secondary,
    },
  },
  comment__delete: {
    fontSize: 16,
    color: theme.palette.text.secondary,
    cursor: "pointer",
    marginLeft: "auto",
    opacity: 0.6,
    "&:hover": {
      opacity: 1,
      color: "#d32f2f",
    },
  },
  comment__form: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 8,
    "& > input": {
      flex: 1,
      minWidth: 0,
      height: 36,
      borderRadius: 18,
      border: `1px solid ${theme.palette.type === "dark" ? "#455a64" : "#cfd8dc"}`,
      backgroundColor: theme.palette.background.paper,
      color: theme.palette.text.primary,
      padding: "0 12px",
      outline: "none",
      fontSize: 13,
      "&:focus": {
        borderColor: theme.palette.primary.main,
      },
    },
    "& > button": {
      height: 36,
      border: 0,
      borderRadius: 18,
      padding: "0 14px",
      cursor: "pointer",
      fontSize: 13,
      fontWeight: 600,
      color: theme.palette.common.white,
      backgroundColor: theme.palette.primary.main,
      transition: "opacity 0.2s ease",
      "&:disabled": {
        cursor: "not-allowed",
        opacity: 0.5,
      },
    },
  },
  repostDialogHint: {
    margin: "0 0 10px",
    fontSize: 13,
    color: theme.palette.text.secondary,
  },
  repostDialogTextarea: {
    width: "100%",
    minHeight: 96,
    borderRadius: 8,
    border: `1px solid ${theme.palette.type === "dark" ? "#455a64" : "#cfd8dc"}`,
    backgroundColor: theme.palette.background.paper,
    color: theme.palette.text.primary,
    padding: 10,
    outline: "none",
    fontSize: 14,
    fontFamily: "inherit",
    resize: "vertical",
    "&:focus": {
      borderColor: theme.palette.primary.main,
    },
    "&:disabled": {
      opacity: 0.7,
      cursor: "not-allowed",
    },
  },
  repostDialogActions: {
    padding: "8px 24px 16px",
    display: "flex",
    gap: 8,
  },
  repostDialogCancelButton: {
    border: `1px solid ${theme.palette.divider}`,
    backgroundColor: "transparent",
    color: theme.palette.text.primary,
    borderRadius: 18,
    padding: "6px 14px",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.6,
    },
  },
  repostDialogSubmitButton: {
    border: 0,
    backgroundColor: theme.palette.primary.main,
    color: theme.palette.common.white,
    borderRadius: 18,
    padding: "6px 14px",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.6,
    },
  },
}));
