import { makeStyles } from "@material-ui/core/styles";
import { darkSecondary, darkPrimary } from "../../assets/Colors";

export default makeStyles((theme) => ({
  header: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 0,
  },
  header__container: {
    minWidth: 1150,
    maxWidth: 1150,
    [theme.breakpoints.down("md")]: {
      minWidth: 940,
      maxWidth: 940,
    },
    [theme.breakpoints.down("sm")]: {
      minWidth: "100%",
    },
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  header__logo: {
    flex: 4,
    height: "100%",
    display: "flex",
    alignItems: "center",
    padding: "0 10px",
    "& > img": {
      height: 32,
      [theme.breakpoints.down("xs")]: {
        height: 28,
      },
    },
    "& > .MuiAvatar-root": {
      display: "none",
      [theme.breakpoints.down("xs")]: {
        display: "block",
        width: 28,
        height: 28,
        marginLeft: 10,
      },
    },
  },
  search__wrapper: {
    width: "60%",
    marginLeft: 10,
    position: "relative",
    [theme.breakpoints.down("xs")]: {
      width: "100%",
    },
  },
  search: {
    width: "100%",
    height: "65%",
    minHeight: 34,
    display: "flex",
    alignItems: "center",
    padding: "0 10px",
    borderRadius: 3,
    border: "1px solid transparent",
    backgroundColor: theme.palette.type === "dark" ? darkSecondary : "#eef3f8",
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    "&:focus-within": {
      borderColor: "#2e7d32",
      boxShadow: "0 0 0 1px rgba(46, 125, 50, 0.15)",
    },
    "& > .MuiSvgIcon-root": {
      color: theme.palette.type === "dark" ? "lightgrey" : "#546e7a",
    },
    "& > input": {
      width: "100%",
      height: "100%",
      marginLeft: 5,
      border: 0,
      outlineWidth: 0,
      color: theme.palette.type === "dark" && "lightgrey",
      backgroundColor: "transparent",
      "&::placeholder": {
        color: theme.palette.type === "dark" && "grey",
      },
    },
  },
  searchDropdown: {
    position: "absolute",
    top: "calc(100% + 6px)",
    left: 0,
    width: "100%",
    zIndex: 1000,
    maxHeight: 400,
    overflowY: "auto",
    borderRadius: 8,
    padding: "4px 0",
    backgroundColor: theme.palette.background.paper,
  },
  searchSectionHeader: {
    padding: "6px 12px 4px",
    fontSize: 12,
    fontWeight: 700,
    color: theme.palette.type === "dark" ? "#9ca3af" : "#6b7280",
  },
  searchResultItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    cursor: "pointer",
    transition: "background-color 0.15s ease",
    "&:hover": {
      backgroundColor: theme.palette.action.hover,
    },
  },
  searchResultAvatar: {
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  searchResultContent: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  searchResultPrimary: {
    fontSize: 14,
    fontWeight: 600,
    color: theme.palette.type === "dark" ? "lightgrey" : "#1d2226",
  },
  searchResultSecondary: {
    fontSize: 12,
    color: theme.palette.type === "dark" ? "#9ca3af" : "#6b7280",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  searchEmptyState: {
    padding: "8px 12px",
    fontSize: 12,
    color: theme.palette.type === "dark" ? "#9ca3af" : "#6b7280",
  },
  header__nav: {
    flex: 5.5,
    height: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    "& > div": {
      flex: 1,
      height: "85%",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      "&:hover": {
        backgroundColor: theme.palette.type === "dark" ? darkSecondary : "lightgrey",
        borderRadius: 2,
      },
    },
    "& > div:nth-child(6)": {
      borderLeft: `1px solid ${theme.palette.type === "dark" ? darkPrimary : "lightgrey"}`,
      borderRight: `1px solid ${theme.palette.type === "dark" ? darkPrimary : "lightgrey"}`,
    },
    [theme.breakpoints.down("xs")]: {
      display: "none",
    },
  },
  signOutButton: {
    marginLeft: 10,
    textTransform: "none",
    borderColor: "#2e7d32",
    color: "#2e7d32",
    fontWeight: 600,
    borderRadius: 999,
    minWidth: 100,
    "&:hover": {
      borderColor: "#1b5e20",
      color: "#1b5e20",
      backgroundColor: "rgba(46, 125, 50, 0.08)",
    },
    [theme.breakpoints.down("xs")]: {
      display: "none",
    },
  },
  header__bottom__nav: {
    display: "none",
    borderRadius: 0,
    boxShadow: "none",
    [theme.breakpoints.down("xs")]: {
      position: "fixed",
      bottom: 0,
      left: 0,
      width: "100%",
      height: 56,
      display: "flex",
      justifyContent: "space-around",
      alignItems: "center",
      padding: "0 6px",
      zIndex: 100,
      backgroundColor: theme.palette.background.paper,
      borderTop: `1px solid ${theme.palette.type === "dark" ? darkSecondary : "#e0e0e0"}`,
    },
  },
  bottomNavIcon: {
    fontSize: 28,
    color: "#757575",
    cursor: "pointer",
    padding: 10,
    borderRadius: 10,
    transition: "color 0.2s ease",
  },
  bottomNavIconActive: {
    color: "#2e7d32",
  },
}));
