import { fade, makeStyles } from "@material-ui/core/styles";
import { darkSecondary } from "../../assets/Colors";

export default makeStyles((theme) => ({
  header: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 0,
    border: "none",
  },
  header__container: {
    minWidth: 1150,
    maxWidth: 1150,
    [theme.breakpoints.down("md")]: {
      minWidth: 940,
      maxWidth: 940,
    },
    [theme.breakpoints.down("sm")]: {
      minWidth: "100%",
    },
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  header__logo: {
    flex: 4,
    height: "100%",
    display: "flex",
    alignItems: "center",
    padding: "0 10px",
    "& > img": {
      height: 32,
      [theme.breakpoints.down("xs")]: {
        height: 28,
      },
    },
    "& > .MuiAvatar-root": {
      display: "none",
      [theme.breakpoints.down("xs")]: {
        display: "block",
        width: 28,
        height: 28,
        marginLeft: 10,
      },
    },
  },
  search__wrapper: {
    width: "60%",
    marginLeft: 10,
    position: "relative",
    [theme.breakpoints.down("xs")]: {
      width: "100%",
    },
  },
  search: {
    width: "100%",
    height: "65%",
    minHeight: 34,
    display: "flex",
    alignItems: "center",
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid transparent",
    backgroundColor: theme.palette.type === "dark" ? darkSecondary : "#eef3f8",
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    "&:focus-within": {
      borderColor: theme.palette.primary.main,
      boxShadow: `0 0 0 1px ${fade(theme.palette.primary.main, 0.15)}`,
    },
    "& > svg": {
      color: theme.palette.type === "dark" ? "lightgrey" : "#546e7a",
    },
    "& > input": {
      width: "100%",
      height: "100%",
      marginLeft: 5,
      border: 0,
      outlineWidth: 0,
      fontSize: 14,
      color: theme.palette.text.primary,
      backgroundColor: "transparent",
      "&::placeholder": {
        color: theme.palette.text.secondary,
      },
    },
  },
  searchDropdown: {
    position: "absolute",
    top: "calc(100% + 6px)",
    left: 0,
    width: "100%",
    zIndex: 1000,
    maxHeight: 400,
    overflowY: "auto",
    borderRadius: 8,
    padding: "4px 0",
    backgroundColor: theme.palette.background.paper,
  },
  searchSectionHeader: {
    padding: "6px 12px 4px",
    fontSize: 12,
    fontWeight: 700,
    color: theme.palette.type === "dark" ? "#9ca3af" : "#6b7280",
  },
  searchResultItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    cursor: "pointer",
    transition: "background-color 0.15s ease",
    "&:hover": {
      backgroundColor: theme.palette.action.hover,
    },
  },
  searchResultAvatar: {
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  searchResultContent: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  searchResultPrimary: {
    fontSize: 14,
    fontWeight: 600,
    color: theme.palette.text.primary,
  },
  searchResultPrimaryRow: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
  },
  searchVerifiedIcon: {
    fontSize: 16,
    color: "#1a73e8",
    flexShrink: 0,
  },
  searchResultSecondary: {
    fontSize: 12,
    color: theme.palette.type === "dark" ? "#9ca3af" : "#6b7280",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  searchEmptyState: {
    padding: "8px 12px",
    fontSize: 12,
    color: theme.palette.type === "dark" ? "#9ca3af" : "#6b7280",
  },
  header__nav: {
    flex: 4,
    height: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    [theme.breakpoints.down("xs")]: {
      display: "none",
    },
  },
  headerNavItem: {
    flex: 1,
    height: "85%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    borderRadius: 4,
    transition: `background-color 0.2s ease`,
    "&:hover": {
      backgroundColor: theme.palette.action.hover,
    },
  },
  headerNavItemActive: {
    "&::after": {
      content: '""',
      position: "absolute",
      left: "18%",
      right: "18%",
      bottom: 0,
      height: 2,
      borderRadius: "2px 2px 0 0",
      backgroundColor: theme.palette.primary.main,
    },
  },
  headerNavDivider: {
    width: 1,
    height: "60%",
    backgroundColor: theme.palette.divider,
    flexShrink: 0,
    margin: "0 4px",
    [theme.breakpoints.down("xs")]: {
      display: "none",
    },
  },
  meTrigger__wrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    flexShrink: 0,
    [theme.breakpoints.down("xs")]: {
      display: "none",
    },
  },
  meTrigger: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    padding: "4px 12px",
    borderRadius: 4,
    transition: "background-color 0.2s ease",
    color: theme.palette.text.secondary,
    "&:hover": {
      backgroundColor: theme.palette.action.hover,
      color: theme.palette.text.primary,
    },
  },
  meTrigger__avatar: {
    width: 24,
    height: 24,
  },
  meTrigger__label: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    "& > span": {
      fontSize: 12,
      fontWeight: 400,
    },
    "& > svg": {
      width: 16,
      height: 16,
    },
  },
  header__bottom__nav: {
    display: "none",
    borderRadius: 0,
    border: "none",
    boxShadow: "none",
    [theme.breakpoints.down("xs")]: {
      position: "fixed",
      bottom: 0,
      left: 0,
      width: "100%",
      height: 56,
      display: "flex",
      justifyContent: "space-around",
      alignItems: "center",
      padding: "0 6px",
      zIndex: 100,
      backgroundColor: theme.palette.background.paper,
      borderTop: `1px solid ${theme.palette.divider}`,
    },
  },
  bottomNavIcon: {
    fontSize: 28,
    color: "#757575",
    cursor: "pointer",
    padding: 10,
    borderRadius: 10,
    transition: "color 0.2s ease",
  },
  bottomNavIconActive: {
    color: theme.palette.primary.main,
  },
}));
